# PANDAS LIBRARY

In [ ]:
Pandas is a Python library used for data analysis, data cleaning, and data manipulation. It helps us organize, analyze, filter, 
and work with structured data such as Excel files, CSV files, and tables.
    Pandas support two types of data structures:-
1]series
2]data frame

### SETUP AND IMPORT

In [4]:
%pip install pandas

Requirement already satisfied: pandas in C:\anaconda\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\anaconda\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\anaconda\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\anaconda\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\anaconda\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

### CREATING SERIES AND DATAFRAME

In [ ]:
#pd.Series()-creates 1D labeled array

In [3]:
s=pd.Series([10,0,30])#, index=['a','b','c'],name='values')
s

0    10
1     0
2    30
dtype: int64

In [4]:
#pd.DataFrame() from a dict of lists -create a labeled 2D table
df=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [4]:
#pd.DataFrame()-from a list of dict
pd.DataFrame([{'a':1,'b':2},{'a':3,'b':4}])

   a  b
0  1  2
1  3  4

In [9]:
#pd.DataFrame()-from a NumPy array
pd.DataFrame(np.arange(6).reshape(2,3),columns=['x','y','z'])

   x  y  z
0  0  1  2
1  3  4  5

### ATTRIBUTES AND INSPECTION

In [10]:
#.shape()-(rows,columns)
df.shape

(4, 3)

In [11]:
#.columns-column labels
df.columns

Index(['name', 'age', 'city'], dtype='str')

In [12]:
#.index-row labels
df.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
#.dtypes-data types of each column
df.dtypes

name      str
age     int64
city      str
dtype: object

In [14]:
#.values-underlying numpy array
df.values

array([['Alice', 25, 'NY'],
       ['Bob', 30, 'LA'],
       ['Charlie', 35, 'SF'],
       ['David', 40, 'NY']], dtype=object)

In [15]:
#.size-total number of elements
df.size

12

In [17]:
#.head()-first n rows [impt]
df.head(2)

    name  age city
0  Alice   25   NY
1    Bob   30   LA

In [18]:
#.tail()-last n rows [impt]
df.tail(2)

      name  age city
2  Charlie   35   SF
3    David   40   NY

In [20]:
#.info()-summary of the dataframe (dtypes,non-null counts) [important]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [21]:
#.describe()-statistical summary of numeric columns
df.describe()

             age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

In [22]:
#.memory_usage()-memory usedc by eah column
df.memory_usage()

Index    132
name      32
age       32
city      32
dtype: int64

### SELECTION AND INDEXING(loc,iloc,at,iat)

In [23]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [24]:
#.set_index()-set a column as the row index
# inplace=Fale ( does not changes the origional dataframe)
df.set_index('name',inplace=False)

         age city
name
Alice     25   NY
Bob       30   LA
Charlie   35   SF
David     40   NY

In [25]:
df.set_index('name',inplace=True) # inplace=True (changes the origional dataframe)

In [26]:
df

         age city
name
Alice     25   NY
Bob       30   LA
Charlie   35   SF
David     40   NY

In [5]:
#columns selection-single columns returns a series
df['age']

0    25
1    30
2    35
3    40
Name: age, dtype: int64

In [6]:
#columns selection-a list of columns returns a dataframe
df[['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [7]:
#.loc[]-select a row by label   (.loc[] stands for location)
df.loc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [8]:
#.loc[]-selects a scalar value by label
df.loc[0,'age']

np.int64(25)

In [9]:
#.loc[]-selects row and columns by label
df.loc[0:2,['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [11]:
#iloc[]-selects a row by integer position
df.iloc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [12]:
df.iloc[0,1]

np.int64(25)

In [13]:
df.iloc[0:2,0:2]

    name  age
0  Alice   25
1    Bob   30

In [14]:
#.at[]-fast scalar access by label
df.at[0,'age']

np.int64(25)

In [15]:
#.iat[]-fast scalar access by integer position
df.iat[0,1]

np.int64(25)

### FILTERING AN BOOLEAN INDEXING

In [16]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [17]:
#simple condition-filter rows matching one condition
df[df['age']>28]

      name  age city
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [19]:
#multiple condition-combine with & (and)/|(or)
df[(df['age']>25) &(df['city']== 'NY')]

    name  age city
3  David   40   NY

In [29]:
df[(df['age']==35) | (df['city']== 'SF')]

      name  age city
2  Charlie   35   SF

In [32]:
#name=bob,or city=ny
df[(df['name']=='Bob') | (df['city']== 'NY')]

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

In [41]:
#.isin()-filter rows where a column matches a set of values
df[df['city'].isin(['NY','LA'])]

    name  age city
0  Alice   25   NY
1    Bob   30   LA
3  David   40   NY

In [40]:
df.query('age>28 and city=="NY"') #.query

    name  age city
3  David   40   NY

In [42]:
#.here()-keep matching values,replace other with NAN
df.where(df['age']>28)

      name   age city
0      NaN   NaN  NaN
1      Bob  30.0   LA
2  Charlie  35.0   SF
3    David  40.0   NY

In [60]:
#.maskopposite to where(),replacing matching values with Nan
df.mask(df['age']>28)

    name   age city
0  Alice  25.0   NY
1    NaN   NaN  NaN
2    NaN   NaN  NaN
3    NaN   NaN  NaN

### ADDING,MODIFYING AND DROPPING COLUMNS/ROWS

In [6]:
df2=df.copy()

In [7]:
df2

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [8]:
#adding a new col from an existing one
df2['senior']=df2['age']>30
df2
df2['junior']=df2['age']<30
df2

      name  age city  senior  junior
0    Alice   25   NY   False    True
1      Bob   30   LA   False   False
2  Charlie   35   SF    True   False
3    David   40   NY    True   False

In [12]:
#adding a computed column
df2['age_plus_5']=df2['age']+5
df2

      name  age city  senior  age_plus_5
0    Alice   25   NY   False          30
1      Bob   30   LA   False          35
2  Charlie   35   SF    True          40
3    David   40   NY    True          45

In [50]:
#.rename()-rename columns
df2.rename(columns={'city':'location'},inplace=True)
df2

      name  age location  senior  age_plus_5
0    Alice   25       NY   False          30
1      Bob   30       LA   False          35
2  Charlie   35       SF    True          40
3    David   40       NY    True          45

In [11]:
#.drop()9columns=...)-drop a column
df2.drop(columns=['junior'], inplace=True)
df2

      name  age city  senior
0    Alice   25   NY   False
1      Bob   30   LA   False
2  Charlie   35   SF    True
3    David   40   NY    True

In [13]:
df2.drop(columns=['age_plus_5'],inplace=True)

In [14]:
df2

      name  age city  senior
0    Alice   25   NY   False
1      Bob   30   LA   False
2  Charlie   35   SF    True
3    David   40   NY    True

In [55]:
#.inset()-insert a column at a specific position
df2.insert(1,'id',range(len(df2)))

In [56]:
df2

      name  id  age location  senior
0    Alice   0   25       NY   False
1      Bob   1   30       LA   False
2  Charlie   2   35       SF    True
3    David   3   40       NY    True

In [58]:
df2.assign(double_age=df2['age']*2)

      name  id  age location  senior  double_age
0    Alice   0   25       NY   False          50
1      Bob   1   30       LA   False          60
2  Charlie   2   35       SF    True          70
3    David   3   40       NY    True          80

### HANDLING MISSING DATA

In [7]:
df_na=pd.DataFrame({'a':[1,np.nan,3],'b':[np.nan,2,3]})
df_na

     a    b
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0

In [8]:
#.isna()-boolean mask of missing values
df_na.isna()

       a      b
0  False   True
1   True  False
2  False  False

In [9]:
#.notna()-opposite of .isna()
df_na.notna()

       a      b
0   True  False
1  False   True
2   True   True

In [10]:
#.isnull().sum()-count missing values per column
df_na.isnull().sum()

a    1
b    1
dtype: int64

In [11]:
#.dropna()-dropping null values/drop rows containing any nan
df_na.dropna()

     a    b
2  3.0  3.0

In [12]:
#.dropna(axis=1)-drop column containing any nan
df_na.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [13]:
#.fillna()-fill missing values with a constant
df_na.fillna(0)

     a    b
0  1.0  0.0
1  0.0  2.0
2  3.0  3.0

In [14]:
#.ffill()-forward fill missing values
df_na.ffill()

     a    b
0  1.0  NaN
1  1.0  2.0
2  3.0  3.0

In [15]:
#.bfill()-backward fill missing values
df_na.bfill()

     a    b
0  1.0  2.0
1  3.0  2.0
2  3.0  3.0

### SORTING AND RANKING

In [18]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [17]:
#.sort_values()
df.sort_values('age') #Sorts rows based on the values in a column.

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [21]:
#sort by multiple columns
#This arranges marks from highest to lowest.
- ascending=True — smallest to largest (default).
- ascending=False — largest to smallest.
df.sort_values(['city','age'],ascending=[True,False])

      name  age city
1      Bob   30   LA
3    David   40   NY
0    Alice   25   NY
2  Charlie   35   SF

In [19]:
#.sort_index()-sorts rows by index
df.sort_index()

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [22]:
#.rank()-rank values within a column
df['age'].rank()

0    1.0
1    2.0
2    3.0
3    4.0
Name: age, dtype: float64

#.nlargest()-top n rows by a column
df.nlargest(2,'age')

In [24]:
#.nsmallest()-bottom n rows by a column
df.nlargest(2,'age')

      name  age city
3    David   40   NY
2  Charlie   35   SF

### AGGREGATION AND STATISTICS

.sum()/.mean()/.median()-basic aggreagtions

In [25]:
df['age'].sum(),df['age'].mean(),df['age'].median()

(np.int64(130), np.float64(32.5), np.float64(32.5))

.std()/.var()-spread of data

In [26]:
df['age'].std(),df['age'].var()

(np.float64(6.454972243679028), np.float64(41.666666666666664))

.min()/.max()-smaallest and largest values

In [27]:
df['age'].max(),df['age'].min()

(np.int64(40), np.int64(25))

.count()-number of not null values

In [28]:
df['age'].count()

np.int64(4)

.agg()-apply multiple aggregation functin at once

In [29]:
df.agg({'age':['mean','max','min']})

       age
mean  32.5
max   40.0
min   25.0

.corr()-correlation matrix of numeric columns

In [30]:
df.corr(numeric_only=True)

     age
age  1.0

.mode()-most frequent occuring value

In [31]:
df['city'].mode()

0    NY
Name: city, dtype: str

### GROUPBY OPERATIONS

In [9]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [10]:
g=df.groupby('city')

In [11]:
#.size()-number of rows in each group
g.size()

city
LA    1
NY    2
SF    1
dtype: int64

In [13]:
#.group then aggregates a single column
g['age'].mean()

city
LA    30.0
NY    32.5
SF    35.0
Name: age, dtype: float64

In [14]:
#.agg() on a groupby-multiply aggregations  per group
g.agg({'age':['mean','sum']})

       age
      mean sum
city
LA    30.0  30
NY    32.5  65
SF    35.0  35

In [16]:
#.apply() on a groupby-custom  function per group
g.apply(lambda x: x['age'].max() - x['age'].min())

city
LA     0
NY    15
SF     0
dtype: int64

In [17]:
add=lambda a,b:a+b

In [18]:
add(4,5)

9

In [ ]:
iterating over groups with a for loop

In [19]:
for name,group in g:
    print(name)
    print(group)

LA
  name  age city
1  Bob   30   LA
NY
    name  age city
0  Alice   25   NY
3  David   40   NY
SF
      name  age city
2  Charlie   35   SF

In [20]:
#.get_group()-retrieve a specific group
g.get_group('NY')

    name  age city
0  Alice   25   NY
3  David   40   NY

In [ ]:
#data

In [25]:
df.to_csv('data.csv',index=False)#converting a data to csv 
pd.read_csv('data.csv')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [27]:
#.to_json()/pd.read_json()-wite and read json fies
df.to_json('data.json',orient='records')
pd.read_json('data.json')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [32]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [5]:
#.to_excel()/pd.read_excel()-write and read excel files(needs openpyxl)
df.to_excel('data.xlsx',index=False)
pd.read_excel('data.xlsx')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [6]:
#.to_dict()-converts a dataframe to a list of dicts
df.to_dict(orient='records')

[{'name': 'Alice', 'age': 25, 'city': 'NY'},
 {'name': 'Bob', 'age': 30, 'city': 'LA'},
 {'name': 'Charlie', 'age': 35, 'city': 'SF'},
 {'name': 'David', 'age': 40, 'city': 'NY'}]

In [7]:
#pd.DataFrame.from_dict()-build a dataframe from a dict
pd.DataFrame.from_dict({'a':[1,2]})

   a
0  1
1  2